### ISSUE TITLE
关于FY4A问题求助

### ISSUE THREAD

**Issue by ZouR-Ma** [Mo-Dabao/BiteFengyun#1]
你好，我现在已经将FY4的文件提取成图片，由于FY4是标称投影（这个投影好像没有国际标准），请问你有试过将标称投影图片转墨卡托投影的经验嘛

**Comment by Mo-Dabao** [comment]
> 你好，我现在已经将FY4的文件提取成图片，由于FY4是标称投影（这个投影好像没有国际标准），请问你有试过将标称投影图片转墨卡托投影的经验嘛

其实就是静止卫星投影，当然是符合国际标准的。FY4A目前的Proj4为
```
+proj=geos +lon_0=104.7 +h=35785855.3 +a=6378137 +b=6356752.3 +units=m
```
当然要先把x和y算出来
可以参考我的一篇公众号：https://mp.weixin.qq.com/s/7DYilkzLluEzxMwBU2Pw4A

有了Proj4就可以和任意投影互转了
